export const PROJECT_DATA = [
  {
    id: 1,
    title: "DevReviews",
    url: "https://app-quiz-eta.vercel.app/",
    headline: "A platform for displaying projects!",
    github: "https://github.com/Ibarra11/app-quiz",
    views: 100,
    likes: 10,
    comments: 30,
    avgRating: 7.5,
    dateCreated: "11/2/24",
  },
  {
    id: 2,
    title: "AwesomeApp",
    url: "https://awesomeapp.com/",
    headline: "An amazing app for productivity!",
    github: "https://github.com/awesomeapp",
    views: 500,
    likes: 50,
    comments: 100,
    avgRating: 9.2,
    dateCreated: "10/25/24",
  },
  {
    id: 3,
    title: "CodeHub",
    url: "https://codehub.io/",
    headline: "Your one-stop destination for coding resources!",
    github: "https://github.com/codehub",
    views: 300,
    likes: 20,
    comments: 50,
    avgRating: 8.0,
    dateCreated: "11/10/24",
  },
  {
    id: 4,
    title: "Amazing Website",
    url: "https://example.com/",
    headline: "A website that will blow your mind!",
    github: "https://github.com/example",
    views: 1000,
    likes: 100,
    comments: 200,
    avgRating: 9.5,
    dateCreated: "12/5/24",
  },
];

export const ITEMS_PER_PAGE = 20;
